import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from pathlib import Path
import argparse

def read_vpr_file(filename):
    """
    Read a VPR file generated by print_vpr_detailed()
    
    Returns:
        List of profiles, where each profile is a dict with:
        - 'bins': bin indices
        - 'heights': bin center heights
        - 'counts': point counts per bin
        - 'reflectivity': average reflectivity values
        - 'valid_mask': boolean mask for bins with points
    """
    profiles = []
    current_profile = {'bins': [], 'heights': [], 'counts': [], 'reflectivity': []}
    
    with open(filename, 'r') as f:
        lines = f.readlines()
    
    for line in lines:
        line = line.strip()
        
        # Skip empty lines (they separate profiles)
        if not line:
            if current_profile['bins']:  # Save the completed profile
                # Convert to numpy arrays
                for key in current_profile:
                    current_profile[key] = np.array(current_profile[key])
                profiles.append(current_profile)
                current_profile = {'bins': [], 'heights': [], 'counts': [], 'reflectivity': []}
            continue
        
        # Skip comment lines
        if line.startswith('#'):
            continue
        
        # Parse data line: bin_index bin_center_height_km point_count avg_reflectivity_dBZ
        parts = line.split()
        if len(parts) >= 4:
            bin_idx = int(parts[0])
            height = float(parts[1])
            count = float(parts[2])  # Can be float from the C code
            refl = float(parts[3])
            
            current_profile['bins'].append(bin_idx)
            current_profile['heights'].append(height)
            current_profile['counts'].append(count)
            current_profile['reflectivity'].append(refl)
    
    # Don't forget the last profile if file doesn't end with empty line
    if current_profile['bins']:
        for key in current_profile:
            current_profile[key] = np.array(current_profile[key])
        profiles.append(current_profile)
    
    # Add valid mask for each profile (ignore bins with zero points)
    for profile in profiles:
        profile['valid_mask'] = profile['counts'] > 0
    
    return profiles

def get_lowest_altitude_reflectivity(profile):
    """
    Get reflectivity at the lowest altitude (smallest height with valid data)
    """
    valid_mask = profile['valid_mask']
    if not np.any(valid_mask):
        return np.nan
    
    # Find the index of the lowest height with valid data
    valid_heights = profile['heights'][valid_mask]
    valid_refl = profile['reflectivity'][valid_mask]
    
    lowest_idx = np.argmin(valid_heights)
    return valid_refl[lowest_idx]

def create_vpr_animation(strat_file, conv_file, output_video='vpr_animation.mp4', 
                         fps=2, dpi=150, figsize=(14, 8)):
    """
    Create an animated video showing stratiform and convective VPR evolution over time
    
    Parameters:
    - strat_file: Path to stratiform VPR file
    - conv_file: Path to convective VPR file
    - output_video: Output video filename
    - fps: Frames per second (default: 2)
    - dpi: Resolution (default: 150)
    - figsize: Figure size (default: (14, 8))
    """
    
    # Read the profiles
    print(f"Reading stratiform profiles from {strat_file}...")
    strat_profiles = read_vpr_file(strat_file)
    print(f"Found {len(strat_profiles)} stratiform profiles")
    
    print(f"Reading convective profiles from {conv_file}...")
    conv_profiles = read_vpr_file(conv_file)
    print(f"Found {len(conv_profiles)} convective profiles")
    
    # Use the minimum number of profiles for animation
    n_frames = min(len(strat_profiles), len(conv_profiles))
    
    if n_frames == 0:
        print("Error: No profiles found in files!")
        return
    
    print(f"Creating animation with {n_frames} frames...")
    
    # Create figure with two subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=figsize)
    
    # Initialize plot elements
    strat_line, = ax1.plot([], [], 'o-', linewidth=2, markersize=6, 
                           color='blue', alpha=0.8, label='Stratiform VPR')
    strat_fill = None
    
    conv_line, = ax2.plot([], [], 's-', linewidth=2, markersize=6, 
                          color='red', alpha=0.8, label='Convective VPR')
    conv_fill = None
    
    # Add title with time/frame indicator
    title_text = ax1.set_title(f'Stratiform VPR - Frame {0}/{n_frames}')
    ax2.set_title(f'Convective VPR - Frame {0}/{n_frames}')
    
    # Labels and limits
    ax1.set_xlabel('Reflectivity (dBZ)')
    ax1.set_ylabel('Height (km)')
    ax1.grid(True, alpha=0.3)
 #   ax1.legend(loc='upper left')
    
    ax2.set_xlabel('Reflectivity (dBZ)')
    ax2.set_ylabel('Height (km)')
    ax2.grid(True, alpha=0.3)
#    ax2.legend(loc='upper left')
    
    # Set reasonable axis limits (will be adjusted dynamically)
    ax1.set_xlim(0, 60)
    ax1.set_ylim(0, 20)
    ax2.set_xlim(0, 60)
    ax2.set_ylim(0, 20)
    
    # Add horizontal lines at 0.5 km intervals for reference
    for ax in [ax1, ax2]:
        for h in range(0, 21, 2):
            ax.axhline(y=h, color='gray', linestyle='--', alpha=0.2, linewidth=0.5)
    
    plt.tight_layout()
    
    # Statistics text box (yellow box) at top-left corner
    stats_text = ax1.text(0.02, 0.98, '', transform=ax1.transAxes, 
                          fontsize=9, verticalalignment='top',
                          bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8),
                          family='monospace')
    
    def update(frame):
        """Update function for animation"""
        # Clear previous fills
        nonlocal strat_fill, conv_fill
        
        # Get profiles for this frame
        strat_profile = strat_profiles[frame]
        conv_profile = conv_profiles[frame]
        
        # Get valid data (non-zero point counts)
        strat_valid = strat_profile['valid_mask']
        conv_valid = conv_profile['valid_mask']
        
        strat_heights = strat_profile['heights'][strat_valid]
        strat_refl = strat_profile['reflectivity'][strat_valid]
        
        conv_heights = conv_profile['heights'][conv_valid]
        conv_refl = conv_profile['reflectivity'][conv_valid]
        
        # Get reflectivity at lowest altitude
        strat_lowest_refl = get_lowest_altitude_reflectivity(strat_profile)
        conv_lowest_refl = get_lowest_altitude_reflectivity(conv_profile)
        
        # Update lines
        strat_line.set_data(strat_refl, strat_heights)
        conv_line.set_data(conv_refl, conv_heights)
        
        # Update fills (using polygon)
        if strat_fill is not None:
            strat_fill.remove()
        if conv_fill is not None:
            conv_fill.remove()
        
        # Create filled area under curves
        if len(strat_refl) > 0:
            strat_fill = ax1.fill_betweenx(strat_heights, 0, strat_refl, 
                                           alpha=0.2, color='blue')
        if len(conv_refl) > 0:
            conv_fill = ax2.fill_betweenx(conv_heights, 0, conv_refl, 
                                          alpha=0.2, color='red')
        
        # Update titles
        ax1.set_title(f'Stratiform VPR - Profile {frame+1}/{n_frames}')
        ax2.set_title(f'Convective VPR - Profile {frame+1}/{n_frames}')
        
        # Update statistics in yellow box (now showing lowest altitude reflectivity instead of max)
        strat_max_z = np.max(strat_refl) if len(strat_refl) > 0 else 0
        strat_max_h = strat_heights[np.argmax(strat_refl)] if len(strat_refl) > 0 else 0
        conv_max_z = np.max(conv_refl) if len(conv_refl) > 0 else 0
        conv_max_h = conv_heights[np.argmax(conv_refl)] if len(conv_refl) > 0 else 0
        
        stats_str = f'Frame {frame+1}/{n_frames}\n'
        stats_str += f'Stratiform: Lowest Z = {strat_lowest_refl:.1f} dBZ\n' if not np.isnan(strat_lowest_refl) else 'Stratiform: Lowest Z = No data\n'
        stats_str += f'Convective: Lowest Z = {conv_lowest_refl:.1f} dBZ\n' if not np.isnan(conv_lowest_refl) else 'Convective: Lowest Z = No data\n'
        stats_str += f'Strat max Z: {strat_max_z:.1f} dBZ @ {strat_max_h:.1f} km\n'
        stats_str += f'Conv max Z: {conv_max_z:.1f} dBZ @ {conv_max_h:.1f} km\n'
        stats_str += f'Strat bins: {np.sum(strat_valid)}/{len(strat_valid)}\n'
        stats_str += f'Conv bins: {np.sum(conv_valid)}/{len(conv_valid)}'
        
        stats_text.set_text(stats_str)
        
        # Auto-adjust x-limits if needed
        all_refl = np.concatenate([strat_refl, conv_refl]) if len(strat_refl) > 0 and len(conv_refl) > 0 else \
                   strat_refl if len(strat_refl) > 0 else conv_refl
        if len(all_refl) > 0:
            max_refl = np.max(all_refl)
            if max_refl > ax1.get_xlim()[1] - 5:
                ax1.set_xlim(0, max_refl + 5)
                ax2.set_xlim(0, max_refl + 5)
        
        return [strat_line, conv_line, stats_text]
    
    # Create animation
    print("Creating animation...")
    anim = animation.FuncAnimation(
        fig, update, frames=n_frames, 
        interval=1000/fps, blit=False, repeat=True
    )
    
    # Save animation
    print(f"Saving animation to {output_video}...")
    writer = animation.FFMpegWriter(fps=fps, metadata=dict(artist='VPR Analysis'), 
                                    bitrate=2000)
    
    # Fallback to Pillow writer if ffmpeg not available
    try:
        anim.save(output_video, writer=writer, dpi=dpi)
    except Exception as e:
        print(f"FFMpegWriter failed: {e}")
        print("Trying with Pillow writer (this may be slower)...")
        anim.save(output_video.replace('.mp4', '.gif'), writer='pillow', fps=fps, dpi=dpi)
        output_video = output_video.replace('.mp4', '.gif')
        print(f"Saved as GIF instead: {output_video}")
    
    plt.close()
    print(f"Animation saved successfully to {output_video}")
    
    return anim

def plot_static_comparison(strat_file, conv_file, output_image='vpr_comparison.png'):
    """
    Create a static figure comparing the last (or most recent) profiles
    """
    strat_profiles = read_vpr_file(strat_file)
    conv_profiles = read_vpr_file(conv_file)
    
    if not strat_profiles or not conv_profiles:
        print("Error: No profiles found!")
        return
    
    # Use the most recent profiles
    strat_last = strat_profiles[-1]
    conv_last = conv_profiles[-1]
    
    # Get valid data
    strat_valid = strat_last['valid_mask']
    conv_valid = conv_last['valid_mask']
    
    # Get reflectivity at lowest altitude
    strat_lowest = get_lowest_altitude_reflectivity(strat_last)
    conv_lowest = get_lowest_altitude_reflectivity(conv_last)
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 8))
    
    # Plot stratiform
    ax1.plot(strat_last['reflectivity'][strat_valid], 
             strat_last['heights'][strat_valid], 
             'o-', linewidth=2, markersize=8, color='blue', label='Stratiform VPR')
    ax1.fill_betweenx(strat_last['heights'][strat_valid], 
                      0, strat_last['reflectivity'][strat_valid], 
                      alpha=0.3, color='blue')
    ax1.set_xlabel('Reflectivity (dBZ)')
    ax1.set_ylabel('Height (km)')
    ax1.set_title(f'Stratiform VPR (Profile {len(strat_profiles)})')
    ax1.grid(True, alpha=0.3)
    ax1.legend(loc='upper left')
    ax1.set_xlim(0, 60)
    ax1.set_ylim(0, 20)
    
    # Add yellow info box
    strat_max_z = np.max(strat_last['reflectivity'][strat_valid]) if np.any(strat_valid) else 0
    strat_max_h = strat_last['heights'][strat_valid][np.argmax(strat_last['reflectivity'][strat_valid])] if np.any(strat_valid) else 0
    
    info_text1 = f'Profile {len(strat_profiles)}\n'
    info_text1 += f'Lowest Z: {strat_lowest:.1f} dBZ\n' if not np.isnan(strat_lowest) else 'Lowest Z: No data\n'
    info_text1 += f'Max Z: {strat_max_z:.1f} dBZ @ {strat_max_h:.1f} km\n'
    info_text1 += f'Bins with data: {np.sum(strat_valid)}/{len(strat_valid)}'
    
    ax1.text(0.02, 0.98, info_text1, transform=ax1.transAxes, 
             fontsize=9, verticalalignment='top',
             bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8),
             family='monospace')
    
    # Plot convective
    ax2.plot(conv_last['reflectivity'][conv_valid], 
             conv_last['heights'][conv_valid], 
             's-', linewidth=2, markersize=8, color='red', label='Convective VPR')
    ax2.fill_betweenx(conv_last['heights'][conv_valid], 
                      0, conv_last['reflectivity'][conv_valid], 
                      alpha=0.3, color='red')
    ax2.set_xlabel('Reflectivity (dBZ)')
    ax2.set_ylabel('Height (km)')
    ax2.set_title(f'Convective VPR (Profile {len(conv_profiles)})')
    ax2.grid(True, alpha=0.3)
    ax2.legend(loc='upper left')
    ax2.set_xlim(0, 60)
    ax2.set_ylim(0, 20)
    
    # Add yellow info box
    conv_max_z = np.max(conv_last['reflectivity'][conv_valid]) if np.any(conv_valid) else 0
    conv_max_h = conv_last['heights'][conv_valid][np.argmax(conv_last['reflectivity'][conv_valid])] if np.any(conv_valid) else 0
    
    info_text2 = f'Profile {len(conv_profiles)}\n'
    info_text2 += f'Lowest Z: {conv_lowest:.1f} dBZ\n' if not np.isnan(conv_lowest) else 'Lowest Z: No data\n'
    info_text2 += f'Max Z: {conv_max_z:.1f} dBZ @ {conv_max_h:.1f} km\n'
    info_text2 += f'Bins with data: {np.sum(conv_valid)}/{len(conv_valid)}'
    
    ax2.text(0.02, 0.98, info_text2, transform=ax2.transAxes, 
             fontsize=9, verticalalignment='top',
             bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8),
             family='monospace')
    
    plt.suptitle('Vertical Profile of Reflectivity (VPR) Comparison', fontsize=14)
    plt.tight_layout()
    plt.savefig(output_image, dpi=150, bbox_inches='tight')
    print(f"Static comparison saved to {output_image}")
    plt.show()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Create VPR animation from C output files')
    parser.add_argument('--strat', type=str, default='outputs/vpr_emp_strat.txt',
                        help='Path to stratiform VPR file')
    parser.add_argument('--conv', type=str, default='outputs/vpr_emp_conv.txt',
                        help='Path to convective VPR file')
    parser.add_argument('--output', type=str, default='vpr_animation.mp4',
                        help='Output video filename')
    parser.add_argument('--fps', type=float, default=2,
                        help='Frames per second (default: 2)')
    parser.add_argument('--dpi', type=int, default=150,
                        help='Resolution DPI (default: 150)')
    parser.add_argument('--static', action='store_true',
                        help='Generate static comparison plot instead of animation')
    parser.add_argument('--static-output', type=str, default='vpr_comparison.png',
                        help='Output image filename for static plot')
    
    args = parser.parse_args()
    
    if args.static:
        plot_static_comparison(args.strat, args.conv, args.static_output)
    else:
        create_vpr_animation(args.strat, args.conv, args.output, 
                            args.fps, args.dpi)
