import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from pathlib import Path
import argparse

def read_vpr_file(filename, has_std=False):
    """
    Read a VPR file generated by print_vpr_detailed()
    
    Parameters:
    - has_std: If True, the file has a 5th column with standard deviation
    
    Returns:
        List of profiles, where each profile is a dict with:
        - 'bins': bin indices
        - 'heights': bin center heights
        - 'counts': point counts per bin
        - 'reflectivity': average reflectivity values
        - 'std': standard deviation values (if available)
        - 'valid_mask': boolean mask for bins with points
    """
    profiles = []
    current_profile = {'bins': [], 'heights': [], 'counts': [], 'reflectivity': []}
    if has_std:
        current_profile['std'] = []
    
    with open(filename, 'r') as f:
        lines = f.readlines()
    
    for line in lines:
        line = line.strip()
        
        # Skip empty lines (they separate profiles)
        if not line:
            if current_profile['bins']:  # Save the completed profile
                # Convert to numpy arrays
                for key in current_profile:
                    current_profile[key] = np.array(current_profile[key])
                profiles.append(current_profile)
                current_profile = {'bins': [], 'heights': [], 'counts': [], 'reflectivity': []}
                if has_std:
                    current_profile['std'] = []
            continue
        
        # Skip comment lines
        if line.startswith('#'):
            continue
        
        # Parse data line: bin_index bin_center_height_km point_count avg_reflectivity_dBZ [std_dev]
        parts = line.split()
        if len(parts) >= 4:
            bin_idx = int(parts[0])
            height = float(parts[1])
            count = float(parts[2])  # Can be float from the C code
            refl = float(parts[3])
            
            current_profile['bins'].append(bin_idx)
            current_profile['heights'].append(height)
            current_profile['counts'].append(count)
            current_profile['reflectivity'].append(refl)
            
            if has_std and len(parts) >= 5:
                std_val = float(parts[4])
                current_profile['std'].append(std_val)
    
    # Don't forget the last profile if file doesn't end with empty line
    if current_profile['bins']:
        for key in current_profile:
            current_profile[key] = np.array(current_profile[key])
        profiles.append(current_profile)
    
    # Add valid mask for each profile (ignore bins with zero points)
    for profile in profiles:
        profile['valid_mask'] = profile['counts'] > 0
    
    return profiles

def read_true_vpr_file(filename):
    """
    Read a true VPR file (can have multiple profiles separated by empty lines)
    
    Returns:
        List of profiles, where each profile is a dict with:
        - 'bins': bin indices
        - 'heights': bin center heights
        - 'reflectivity': reflectivity values
        - 'valid_mask': boolean mask for bins with valid data (non-zero reflectivity)
    """
    profiles = []
    current_profile = {'bins': [], 'heights': [], 'reflectivity': []}
    
    with open(filename, 'r') as f:
        lines = f.readlines()
    
    for line in lines:
        line = line.strip()
        
        # Skip empty lines (they separate profiles)
        if not line:
            if current_profile['bins']:  # Save the completed profile
                # Convert to numpy arrays
                for key in current_profile:
                    current_profile[key] = np.array(current_profile[key])
                # Add valid mask (reflectivity > 0)
                current_profile['valid_mask'] = current_profile['reflectivity'] > 0
                profiles.append(current_profile)
                current_profile = {'bins': [], 'heights': [], 'reflectivity': []}
            continue
        
        # Skip comment lines
        if line.startswith('#'):
            continue
        
        # Parse data line: bin_index bin_center_height_km reflectivity_dBZ
        parts = line.split()
        if len(parts) >= 3:
            bin_idx = int(parts[0])
            height = float(parts[1])
            refl = float(parts[2])
            
            current_profile['bins'].append(bin_idx)
            current_profile['heights'].append(height)
            current_profile['reflectivity'].append(refl)
    
    # Don't forget the last profile if file doesn't end with empty line
    if current_profile['bins']:
        for key in current_profile:
            current_profile[key] = np.array(current_profile[key])
        current_profile['valid_mask'] = current_profile['reflectivity'] > 0
        profiles.append(current_profile)
    
    return profiles

def get_lowest_altitude_reflectivity(profile):
    """
    Get reflectivity at the lowest altitude (smallest height with valid data)
    """
    valid_mask = profile['valid_mask']
    if not np.any(valid_mask):
        return np.nan
    
    # Find the index of the lowest height with valid data
    valid_heights = profile['heights'][valid_mask]
    valid_refl = profile['reflectivity'][valid_mask]
    
    lowest_idx = np.argmin(valid_heights)
    return valid_refl[lowest_idx]

def create_vpr_animation(output_video='vpr_animation.mp4', 
                         fps=2, dpi=150, figsize=(14, 8)):
    """
    Create an animated video showing stratiform and convective VPR evolution over time
    
    Parameters:
    - output_video: Output video filename
    - fps: Frames per second (default: 2)
    - dpi: Resolution (default: 150)
    - figsize: Figure size (default: (14, 8))
    """
    
    # Fixed filenames
    strat_file = 'outputs/75km away/vpr_emp_strat.txt'
    conv_file = 'outputs/75km away/vpr_emp_conv.txt'
    strat_ad_file = 'outputs/75km away/vpr_emp_strat_ad.txt'
    conv_ad_file = 'outputs/75km away/vpr_emp_conv_ad.txt'
    strat_true_file = 'outputs/75km away/vpr_true_strat.txt'
    conv_true_file = 'outputs/75km away/vpr_true_conv.txt'
    
    # Read the profiles (both non-adaptive and adaptive have std dev)
    print(f"Reading stratiform profiles from {strat_file}...")
    strat_profiles = read_vpr_file(strat_file, has_std=True)
    print(f"Found {len(strat_profiles)} stratiform profiles")
    
    print(f"Reading convective profiles from {conv_file}...")
    conv_profiles = read_vpr_file(conv_file, has_std=True)
    print(f"Found {len(conv_profiles)} convective profiles")
    
    # Read AD files (they also have std dev)
    print(f"Reading stratiform AD profiles from {strat_ad_file}...")
    strat_ad_profiles = read_vpr_file(strat_ad_file, has_std=True)
    print(f"Found {len(strat_ad_profiles)} stratiform AD profiles")
    
    print(f"Reading convective AD profiles from {conv_ad_file}...")
    conv_ad_profiles = read_vpr_file(conv_ad_file, has_std=True)
    print(f"Found {len(conv_ad_profiles)} convective AD profiles")
    
    # Read true VPRs (these can have multiple profiles)
    print(f"Reading true stratiform VPR from {strat_true_file}...")
    strat_true_profiles = read_true_vpr_file(strat_true_file)
    print(f"Found {len(strat_true_profiles)} true stratiform profiles")
    
    print(f"Reading true convective VPR from {conv_true_file}...")
    conv_true_profiles = read_true_vpr_file(conv_true_file)
    print(f"Found {len(conv_true_profiles)} true convective profiles")
    
    # Use the minimum number of profiles for animation
    n_frames = min(len(strat_profiles), len(conv_profiles), 
                   len(strat_ad_profiles), len(conv_ad_profiles),
                   len(strat_true_profiles), len(conv_true_profiles))
    
    if n_frames == 0:
        print("Error: No profiles found in files!")
        return
    
    print(f"Creating animation with {n_frames} frames...")
    
    # Create figure with two subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=figsize)
    
    # Initialize plot elements for non-adaptive profiles (solid lines)
    strat_line, = ax1.plot([], [], 'o-', linewidth=1, markersize=3, 
                           color='blue', alpha=0.8, label='Non-adaptive VPR')
    strat_ci_fill = None
    
    # Initialize plot elements for adaptive profiles (dotted lines)
    strat_ad_line, = ax1.plot([], [], '^:', linewidth=1.5, markersize=3,
                              color='blue', alpha=0.8, label='Adaptive VPR')
    strat_ad_ci_fill = None
    
    # Initialize plot elements for true profiles (solid black line)
    strat_true_line, = ax1.plot([], [], 'k-', linewidth=1.5, alpha=0.7, 
                                 label='True VPR', zorder=5)
    
    conv_line, = ax2.plot([], [], 's-', linewidth=1, markersize=3, 
                          color='red', alpha=0.8, label='Non-adaptive VPR')
    conv_ci_fill = None
    
    conv_ad_line, = ax2.plot([], [], 'v:', linewidth=1.5, markersize=3,
                             color='red', alpha=0.8, label='Adaptive VPR')
    conv_ad_ci_fill = None
    
    conv_true_line, = ax2.plot([], [], 'k-', linewidth=1.5, alpha=0.7,
                                label='True VPR', zorder=5)
    
    # Add title with time/frame indicator
    ax1.set_title(f'Stratiform VPR')
    ax2.set_title(f'Convective VPR')
    
    # Labels and limits
    ax1.set_xlabel('Reflectivity (dBZ)')
    ax1.set_ylabel('Height (km)')
    ax1.grid(True, alpha=0.3)
    ax1.legend(loc='upper right')
    
    ax2.set_xlabel('Reflectivity (dBZ)')
    ax2.set_ylabel('Height (km)')
    ax2.grid(True, alpha=0.3)
    ax2.legend(loc='upper right')
    
    # Set reasonable axis limits (will be adjusted dynamically)
    ax1.set_xlim(0, 60)
    ax1.set_ylim(0, 20)
    ax2.set_xlim(0, 60)
    ax2.set_ylim(0, 20)
    
    # Add horizontal lines at 2 km intervals for reference
    for ax in [ax1, ax2]:
        for h in range(0, 21, 2):
            ax.axhline(y=h, color='gray', linestyle='--', alpha=0.2, linewidth=0.5)
    
    plt.tight_layout()
    
    # Statistics text box (yellow box) at top-left corner
    stats_text = ax1.text(0.02, 0.98, '', transform=ax1.transAxes, 
                          fontsize=9, verticalalignment='top',
                          bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8),
                          family='monospace')
    
    def update(frame):
        """Update function for animation"""
        # Clear previous fills
        nonlocal strat_ci_fill, conv_ci_fill, strat_ad_ci_fill, conv_ad_ci_fill
        
        # Get profiles for this frame
        strat_profile = strat_profiles[frame]
        conv_profile = conv_profiles[frame]
        strat_ad_profile = strat_ad_profiles[frame]
        conv_ad_profile = conv_ad_profiles[frame]
        strat_true_profile = strat_true_profiles[frame]
        conv_true_profile = conv_true_profiles[frame]
        
        # Get valid data for non-adaptive
        strat_valid = strat_profile['valid_mask']
        conv_valid = conv_profile['valid_mask']
        
        strat_heights = strat_profile['heights'][strat_valid]
        strat_refl = strat_profile['reflectivity'][strat_valid]
        strat_std = strat_profile['std'][strat_valid] if 'std' in strat_profile else None
        
        conv_heights = conv_profile['heights'][conv_valid]
        conv_refl = conv_profile['reflectivity'][conv_valid]
        conv_std = conv_profile['std'][conv_valid] if 'std' in conv_profile else None
        
        # Get valid data for adaptive
        strat_ad_valid = strat_ad_profile['valid_mask']
        conv_ad_valid = conv_ad_profile['valid_mask']
        
        strat_ad_heights = strat_ad_profile['heights'][strat_ad_valid]
        strat_ad_refl = strat_ad_profile['reflectivity'][strat_ad_valid]
        strat_ad_std = strat_ad_profile['std'][strat_ad_valid] if 'std' in strat_ad_profile else None
        
        conv_ad_heights = conv_ad_profile['heights'][conv_ad_valid]
        conv_ad_refl = conv_ad_profile['reflectivity'][conv_ad_valid]
        conv_ad_std = conv_ad_profile['std'][conv_ad_valid] if 'std' in conv_ad_profile else None
        
        # Get valid data for true profiles
        strat_true_valid = strat_true_profile['valid_mask']
        conv_true_valid = conv_true_profile['valid_mask']
        
        strat_true_heights = strat_true_profile['heights'][strat_true_valid]
        strat_true_refl = strat_true_profile['reflectivity'][strat_true_valid]
        
        conv_true_heights = conv_true_profile['heights'][conv_true_valid]
        conv_true_refl = conv_true_profile['reflectivity'][conv_true_valid]
        
        # Get reflectivity at lowest altitude
        strat_lowest_refl = get_lowest_altitude_reflectivity(strat_profile)
        conv_lowest_refl = get_lowest_altitude_reflectivity(conv_profile)
        strat_ad_lowest_refl = get_lowest_altitude_reflectivity(strat_ad_profile)
        conv_ad_lowest_refl = get_lowest_altitude_reflectivity(conv_ad_profile)
        
        # Update lines
        strat_line.set_data(strat_refl, strat_heights)
        conv_line.set_data(conv_refl, conv_heights)
        strat_ad_line.set_data(strat_ad_refl, strat_ad_heights)
        conv_ad_line.set_data(conv_ad_refl, conv_ad_heights)
        strat_true_line.set_data(strat_true_refl, strat_true_heights)
        conv_true_line.set_data(conv_true_refl, conv_true_heights)
        
        # Remove previous fills
        if strat_ci_fill is not None:
            strat_ci_fill.remove()
        if conv_ci_fill is not None:
            conv_ci_fill.remove()
        if strat_ad_ci_fill is not None:
            strat_ad_ci_fill.remove()
        if conv_ad_ci_fill is not None:
            conv_ad_ci_fill.remove()
        
        # Create confidence interval shading for non-adaptive (3 sigma = 99.7% confidence)
        if strat_std is not None and len(strat_refl) > 0:
            lower_bound = strat_refl - 3 * strat_std
            upper_bound = strat_refl + 3 * strat_std
            lower_bound = np.maximum(lower_bound, 0)
            
            strat_ci_fill = ax1.fill_betweenx(strat_heights, lower_bound, upper_bound,
                                              alpha=0.15, color='blue', 
                                              label='±3σ (99.7% CI)')
        
        if conv_std is not None and len(conv_refl) > 0:
            lower_bound = conv_refl - 3 * conv_std
            upper_bound = conv_refl + 3 * conv_std
            lower_bound = np.maximum(lower_bound, 0)
            
            conv_ci_fill = ax2.fill_betweenx(conv_heights, lower_bound, upper_bound,
                                             alpha=0.15, color='red',
                                             label='±3σ (99.7% CI)')
        
        # Create confidence interval shading for adaptive (3 sigma = 99.7% confidence)
        if strat_ad_std is not None and len(strat_ad_refl) > 0:
            lower_bound = strat_ad_refl - 3 * strat_ad_std
            upper_bound = strat_ad_refl + 3 * strat_ad_std
            lower_bound = np.maximum(lower_bound, 0)
            
            strat_ad_ci_fill = ax1.fill_betweenx(strat_ad_heights, lower_bound, upper_bound,
                                                 alpha=0.1, color='cyan', 
                                                 label='Adaptive ±3σ')
        
        if conv_ad_std is not None and len(conv_ad_refl) > 0:
            lower_bound = conv_ad_refl - 3 * conv_ad_std
            upper_bound = conv_ad_refl + 3 * conv_ad_std
            lower_bound = np.maximum(lower_bound, 0)
            
            conv_ad_ci_fill = ax2.fill_betweenx(conv_ad_heights, lower_bound, upper_bound,
                                                alpha=0.1, color='orange',
                                                label='Adaptive ±3σ')
        
        # Update titles with frame number
        ax1.set_title(f'Stratiform VPR - Profile {frame+1}/{n_frames}')
        ax2.set_title(f'Convective VPR - Profile {frame+1}/{n_frames}')
        
        # Update statistics in yellow box
        strat_max_z = np.max(strat_refl) if len(strat_refl) > 0 else 0
        strat_max_h = strat_heights[np.argmax(strat_refl)] if len(strat_refl) > 0 else 0
        conv_max_z = np.max(conv_refl) if len(conv_refl) > 0 else 0
        conv_max_h = conv_heights[np.argmax(conv_refl)] if len(conv_refl) > 0 else 0
        
        stats_str = f'Frame {frame+1}/{n_frames}\n'
        stats_str += f'Strat (non-ad): Lowest Z = {strat_lowest_refl:.1f} dBZ\n' if not np.isnan(strat_lowest_refl) else 'Strat (non-ad): Lowest Z = No data\n'
        stats_str += f'Strat (ad): Lowest Z = {strat_ad_lowest_refl:.1f} dBZ\n' if not np.isnan(strat_ad_lowest_refl) else 'Strat (ad): Lowest Z = No data\n'
        stats_str += f'Conv (non-ad): Lowest Z = {conv_lowest_refl:.1f} dBZ\n' if not np.isnan(conv_lowest_refl) else 'Conv (non-ad): Lowest Z = No data\n'
        stats_str += f'Conv (ad): Lowest Z = {conv_ad_lowest_refl:.1f} dBZ\n' if not np.isnan(conv_ad_lowest_refl) else 'Conv (ad): Lowest Z = No data\n'
        stats_str += f'Strat max Z: {strat_max_z:.1f} dBZ @ {strat_max_h:.1f} km\n'
        stats_str += f'Conv max Z: {conv_max_z:.1f} dBZ @ {conv_max_h:.1f} km\n'
        stats_str += f'Strat bins: {np.sum(strat_valid)}/{len(strat_valid)}\n'
        stats_str += f'Conv bins: {np.sum(conv_valid)}/{len(conv_valid)}'
        
        stats_text.set_text(stats_str)
        
        # Auto-adjust x-limits if needed
        all_refl = []
        if len(strat_refl) > 0:
            all_refl.extend(strat_refl)
        if len(conv_refl) > 0:
            all_refl.extend(conv_refl)
        if len(strat_ad_refl) > 0:
            all_refl.extend(strat_ad_refl)
        if len(conv_ad_refl) > 0:
            all_refl.extend(conv_ad_refl)
        if len(strat_true_refl) > 0:
            all_refl.extend(strat_true_refl)
        if len(conv_true_refl) > 0:
            all_refl.extend(conv_true_refl)
        
        if len(all_refl) > 0:
            max_refl = np.max(all_refl)
            if max_refl > ax1.get_xlim()[1] - 5:
                ax1.set_xlim(0, max_refl + 5)
                ax2.set_xlim(0, max_refl + 5)
        
        # Return all artists
        artists = [strat_line, strat_ad_line, strat_true_line, 
                   conv_line, conv_ad_line, conv_true_line, stats_text]
        
        return artists
    
    # Create animation
    print("Creating animation...")
    anim = animation.FuncAnimation(
        fig, update, frames=n_frames, 
        interval=1000/fps, blit=False, repeat=True
    )
    
    # Save animation
    print(f"Saving animation to {output_video}...")
    writer = animation.FFMpegWriter(fps=fps, metadata=dict(artist='VPR Analysis'), 
                                    bitrate=2000)
    
    # Fallback to Pillow writer if ffmpeg not available
    try:
        anim.save(output_video, writer=writer, dpi=dpi)
    except Exception as e:
        print(f"FFMpegWriter failed: {e}")
        print("Trying with Pillow writer (this may be slower)...")
        anim.save(output_video.replace('.mp4', '.gif'), writer='pillow', fps=fps, dpi=dpi)
        output_video = output_video.replace('.mp4', '.gif')
        print(f"Saved as GIF instead: {output_video}")
    
    plt.close()
    print(f"Animation saved successfully to {output_video}")
    
    return anim

def plot_static_comparison(output_image='vpr_comparison.png'):
    """
    Create a static figure comparing the last (or most recent) profiles
    """
    # Fixed filenames
    strat_file = 'outputs/vpr_emp_strat.txt'
    conv_file = 'outputs/vpr_emp_conv.txt'
    strat_ad_file = 'outputs/vpr_emp_strat_ad.txt'
    conv_ad_file = 'outputs/vpr_emp_conv_ad.txt'
    strat_true_file = 'outputs/vpr_true_strat.txt'
    conv_true_file = 'outputs/vpr_true_conv.txt'
    
    strat_profiles = read_vpr_file(strat_file, has_std=True)
    conv_profiles = read_vpr_file(conv_file, has_std=True)
    strat_ad_profiles = read_vpr_file(strat_ad_file, has_std=True)
    conv_ad_profiles = read_vpr_file(conv_ad_file, has_std=True)
    strat_true_profiles = read_true_vpr_file(strat_true_file)
    conv_true_profiles = read_true_vpr_file(conv_true_file)
    
    if not strat_profiles or not conv_profiles:
        print("Error: No profiles found!")
        return
    
    # Use the most recent profiles
    strat_last = strat_profiles[-1]
    conv_last = conv_profiles[-1]
    strat_ad_last = strat_ad_profiles[-1]
    conv_ad_last = conv_ad_profiles[-1]
    strat_true_last = strat_true_profiles[-1]
    conv_true_last = conv_true_profiles[-1]
    
    # Get valid data
    strat_valid = strat_last['valid_mask']
    conv_valid = conv_last['valid_mask']
    strat_ad_valid = strat_ad_last['valid_mask']
    conv_ad_valid = conv_ad_last['valid_mask']
    strat_true_valid = strat_true_last['valid_mask']
    conv_true_valid = conv_true_last['valid_mask']
    
    # Get reflectivity at lowest altitude
    strat_lowest = get_lowest_altitude_reflectivity(strat_last)
    conv_lowest = get_lowest_altitude_reflectivity(conv_last)
    strat_ad_lowest = get_lowest_altitude_reflectivity(strat_ad_last)
    conv_ad_lowest = get_lowest_altitude_reflectivity(conv_ad_last)
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 8))
    
    # Plot true VPRs
    if np.any(strat_true_valid):
        ax1.plot(strat_true_last['reflectivity'][strat_true_valid], 
                 strat_true_last['heights'][strat_true_valid], 
                 'k-', linewidth=2, alpha=0.7, label='True VPR', zorder=5)
    
    if np.any(conv_true_valid):
        ax2.plot(conv_true_last['reflectivity'][conv_true_valid], 
                 conv_true_last['heights'][conv_true_valid], 
                 'k-', linewidth=2, alpha=0.7, label='True VPR', zorder=5)
    
    # Plot stratiform non-adaptive
    if 'std' in strat_last and np.any(strat_valid):
        strat_heights_valid = strat_last['heights'][strat_valid]
        strat_refl_valid = strat_last['reflectivity'][strat_valid]
        strat_std_valid = strat_last['std'][strat_valid]
        
        lower_bound = strat_refl_valid - 3 * strat_std_valid
        upper_bound = strat_refl_valid + 3 * strat_std_valid
        lower_bound = np.maximum(lower_bound, 0)
        
        ax1.fill_betweenx(strat_heights_valid, lower_bound, upper_bound,
                          alpha=0.15, color='blue', label='Non-ad ±3σ (99.7% CI)')
    
    if np.any(strat_valid):
        ax1.plot(strat_last['reflectivity'][strat_valid], 
                 strat_last['heights'][strat_valid], 
                 'o-', linewidth=1.5, markersize=4, color='blue', 
                 label='Non-adaptive VPR')
    
    # Plot stratiform adaptive
    if 'std' in strat_ad_last and np.any(strat_ad_valid):
        strat_ad_heights_valid = strat_ad_last['heights'][strat_ad_valid]
        strat_ad_refl_valid = strat_ad_last['reflectivity'][strat_ad_valid]
        strat_ad_std_valid = strat_ad_last['std'][strat_ad_valid]
        
        lower_bound = strat_ad_refl_valid - 3 * strat_ad_std_valid
        upper_bound = strat_ad_refl_valid + 3 * strat_ad_std_valid
        lower_bound = np.maximum(lower_bound, 0)
        
        ax1.fill_betweenx(strat_ad_heights_valid, lower_bound, upper_bound,
                          alpha=0.1, color='cyan', label='Adaptive ±3σ')
    
    if np.any(strat_ad_valid):
        ax1.plot(strat_ad_last['reflectivity'][strat_ad_valid],
                strat_ad_last['heights'][strat_ad_valid],
                '^:', linewidth=1.5, markersize=4, color='blue', 
                label='Adaptive VPR')
    
    ax1.set_xlabel('Reflectivity (dBZ)')
    ax1.set_ylabel('Height (km)')
    ax1.set_title(f'Stratiform VPR (Profile {len(strat_profiles)})')
    ax1.grid(True, alpha=0.3)
    ax1.legend(loc='upper left', fontsize=8)
    ax1.set_xlim(0, 60)
    ax1.set_ylim(0, 20)
    
    # Add yellow info box
    strat_max_z = np.max(strat_last['reflectivity'][strat_valid]) if np.any(strat_valid) else 0
    strat_max_h = strat_last['heights'][strat_valid][np.argmax(strat_last['reflectivity'][strat_valid])] if np.any(strat_valid) else 0
    
    info_text1 = f'Profile {len(strat_profiles)}\n'
    info_text1 += f'Non-ad lowest Z: {strat_lowest:.1f} dBZ\n' if not np.isnan(strat_lowest) else 'Non-ad lowest Z: No data\n'
    info_text1 += f'Adaptive lowest Z: {strat_ad_lowest:.1f} dBZ\n' if not np.isnan(strat_ad_lowest) else 'Adaptive lowest Z: No data\n'
    info_text1 += f'Max Z: {strat_max_z:.1f} dBZ @ {strat_max_h:.1f} km\n'
    info_text1 += f'Bins with data: {np.sum(strat_valid)}/{len(strat_valid)}'
    
    ax1.text(0.02, 0.98, info_text1, transform=ax1.transAxes, 
             fontsize=8, verticalalignment='top',
             bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8),
             family='monospace')
    
    # Plot convective non-adaptive
    if 'std' in conv_last and np.any(conv_valid):
        conv_heights_valid = conv_last['heights'][conv_valid]
        conv_refl_valid = conv_last['reflectivity'][conv_valid]
        conv_std_valid = conv_last['std'][conv_valid]
        
        lower_bound = conv_refl_valid - 3 * conv_std_valid
        upper_bound = conv_refl_valid + 3 * conv_std_valid
        lower_bound = np.maximum(lower_bound, 0)
        
        ax2.fill_betweenx(conv_heights_valid, lower_bound, upper_bound,
                          alpha=0.15, color='red', label='Non-ad ±3σ (99.7% CI)')
    
    if np.any(conv_valid):
        ax2.plot(conv_last['reflectivity'][conv_valid], 
                 conv_last['heights'][conv_valid], 
                 's-', linewidth=1.5, markersize=4, color='red', 
                 label='Non-adaptive VPR')
    
    # Plot convective adaptive
    if 'std' in conv_ad_last and np.any(conv_ad_valid):
        conv_ad_heights_valid = conv_ad_last['heights'][conv_ad_valid]
        conv_ad_refl_valid = conv_ad_last['reflectivity'][conv_ad_valid]
        conv_ad_std_valid = conv_ad_last['std'][conv_ad_valid]
        
        lower_bound = conv_ad_refl_valid - 3 * conv_ad_std_valid
        upper_bound = conv_ad_refl_valid + 3 * conv_ad_std_valid
        lower_bound = np.maximum(lower_bound, 0)
        
        ax2.fill_betweenx(conv_ad_heights_valid, lower_bound, upper_bound,
                          alpha=0.1, color='orange', label='Adaptive ±3σ')
    
    if np.any(conv_ad_valid):
        ax2.plot(conv_ad_last['reflectivity'][conv_ad_valid],
                conv_ad_last['heights'][conv_ad_valid],
                'v:', linewidth=1.5, markersize=4, color='red', 
                label='Adaptive VPR')
    
    ax2.set_xlabel('Reflectivity (dBZ)')
    ax2.set_ylabel('Height (km)')
    ax2.set_title(f'Convective VPR (Profile {len(conv_profiles)})')
    ax2.grid(True, alpha=0.3)
    ax2.legend(loc='upper left', fontsize=8)
    ax2.set_xlim(0, 60)
    ax2.set_ylim(0, 20)
    
    # Add yellow info box
    conv_max_z = np.max(conv_last['reflectivity'][conv_valid]) if np.any(conv_valid) else 0
    conv_max_h = conv_last['heights'][conv_valid][np.argmax(conv_last['reflectivity'][conv_valid])] if np.any(conv_valid) else 0
    
    info_text2 = f'Profile {len(conv_profiles)}\n'
    info_text2 += f'Non-ad lowest Z: {conv_lowest:.1f} dBZ\n' if not np.isnan(conv_lowest) else 'Non-ad lowest Z: No data\n'
    info_text2 += f'Adaptive lowest Z: {conv_ad_lowest:.1f} dBZ\n' if not np.isnan(conv_ad_lowest) else 'Adaptive lowest Z: No data\n'
    info_text2 += f'Max Z: {conv_max_z:.1f} dBZ @ {conv_max_h:.1f} km\n'
    info_text2 += f'Bins with data: {np.sum(conv_valid)}/{len(conv_valid)}'
    
    ax2.text(0.02, 0.98, info_text2, transform=ax2.transAxes, 
             fontsize=8, verticalalignment='top',
             bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8),
             family='monospace')
    
    plt.suptitle('Vertical Profile of Reflectivity (VPR) Comparison', fontsize=14)
    plt.tight_layout()
    plt.savefig(output_image, dpi=150, bbox_inches='tight')
    print(f"Static comparison saved to {output_image}")
    plt.show()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Create VPR animation from fixed file names')
    parser.add_argument('--output', type=str, default='outputs/AAFIGUREvpr_animation.mp4',
                        help='Output video filename')
    parser.add_argument('--fps', type=float, default=2,
                        help='Frames per second (default: 2)')
    parser.add_argument('--dpi', type=int, default=150,
                        help='Resolution DPI (default: 150)')
    parser.add_argument('--static', action='store_true',
                        help='Generate static comparison plot instead of animation')
    parser.add_argument('--static-output', type=str, default='vpr_comparison.png',
                        help='Output image filename for static plot')
    
    args = parser.parse_args()
    
    if args.static:
        plot_static_comparison(args.static_output)
    else:
        create_vpr_animation(args.output, args.fps, args.dpi)
